version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "rust"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      all-dependencies:
        patterns:
          - "*"
